/* Здесь может быть любой oracle sql код */

-- Создание таблицы "students"
CREATE TABLE students (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    enrollment_year NUMBER
);

-- Вставка данных в таблицу "students"
INSERT INTO students (first_name, last_name, enrollment_year) VALUES
('John', 'Doe', 2021),
('Jane', 'Smith', 2020),
('Emily', 'Johnson', 2022);

-- Запрос для получения всех студентов
SELECT * FROM students;